name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          PROD_DATABASE_URL: ${{secrets.PROD_DATABASE_URL}}
          PROD_USERNAME: ${{sectrets.PROD_USERNAME}}
          PROD_PASSWORD: ${{secrets.PROD_PASSWORD}}

        run: mvn -B clean verify -DskipTests
